### ISSUE TITLE
Unable to use the -l option

### ISSUE THREAD

**Issue by mosser** [MarcelRobeer/VisualNarrator#12]
Hi, 

I tried to use _VisualNarrator_ while keeping a link between concepts and stories. However, when running the tool using the `-l` option, it generates an error at runtime:

```
azrael:tmp mosser$ python run.py output/example_stories.txt -p -l 
Initializing Natural Language Processor. . .
Traceback (most recent call last):
  File "run.py", line 314, in <module>
    program()
  File "run.py", line 302, in program
    return main(args.filename, args.system_name, args.print_us, args.print_ont, args.statistics, args.link, args.prolog, args.json, args.per_role, args.threshold, args.base_weight, weights, spacy_nlp)
  File "run.py", line 97, in main
    out = patterns.make(systemname, threshold, link)
  File "/usr/src/app/vn/pattern.py", line 26, in make
    self.link_to_story(self.onto.classes, self.user_stories)
  File "/usr/src/app/vn/pattern.py", line 46, in link_to_story
    parts = self.get_parts(cl.name, s)
  File "/usr/src/app/vn/pattern.py", line 143, in get_parts
    ends_compounds = flatten(story.ends.compounds)
NameError: name 'flatten' is not defined
```

Any ideas?

Ps. In the meanwhile, I can rely on the generated prolog file to recreate this information.

**Comment by MarcelRobeer** [comment]
Resolved in commit 98e4d72
