### ISSUE TITLE
User Story file giving error at getWT function.

### ISSUE THREAD

**Issue by ashwarhussain** [MarcelRobeer/VisualNarrator#16]
Hello, I am trying to use the attached file with user stories to get an output but I am getting the below specified error.

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    main()
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\cli.py", line 104, in main
    stories = Reader.parse(args.filename))
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\vn.py", line 101, in run
    self._get_gen(us_instances, m, systemname, print_ont, log_time=self.time)
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\utils\utility.py", line 78, in timed
    result = method(*args, **kw)
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\vn.py", line 239, in _get_gen
    out = patterns.make(systemname, self.threshold, self.link)
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\pattern.py", line 26, in make
    self.onto = pf.make_patterns(self.user_stories, threshold)
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\pattern.py", line 229, in make_patterns
    pi.identify(story)
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\pattern.py", line 339, in identify
    self.identify_subj_dobj(story, 'ends')
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\pattern.py", line 421, in identify_subj_dobj
    w_do = [self.getwt(x) for x in do]
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\pattern.py", line 421, in <listcomp>
    w_do = [self.getwt(x) for x in do]
  File "C:\Code\Machine Learning\IIM\VisualNarrator-master\VisualNarrator-master\vn\pattern.py", line 477, in getwt
    if str.lower(token.text) == str.lower(wt.token.text):
AttributeError: 'NoneType' object has no attribute 'text'
[g10-scrumalliance.txt](https://github.com/MarcelRobeer/VisualNarrator/files/3261319/g10-scrumalliance.txt)

**Comment by MarcelRobeer** [comment]
VN was assuming there was a relationship in the ends "we can connect" of user story "As a site member, I want to send an email to any member via a form, so that we can connect." without the verb 'connect' referring to any object. The issue should be resolved in the last commit.

**Comment by ashwarhussain** [comment]
Thanks it helped .. I was able to parse this file .. thanks again ..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ashwarhussain** [comment]
I would have to re-open this issue again. attached file when tried gave me the same error. 
**Also VN should have the capability to move on with the user stories which it could parse instead of giving an error and halting the entire process**. 
[SIAnalytics.txt](https://github.com/MarcelRobeer/VisualNarrator/files/3391295/SIAnalytics.txt)
