### ISSUE TITLE
User Story file giving error at getWT function

### ISSUE THREAD

**Issue by ashwarhussain** [MarcelRobeer/VisualNarrator#17]
VN should not have a hard stop when its NOT able to parse a single User story .. 
[SIAnalytics.txt](https://github.com/MarcelRobeer/VisualNarrator/files/3391399/SIAnalytics.txt)

attached file is giving an error 
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    main()
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\cli.py", line 104, in main
    stories = Reader.parse(args.filename))
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\vn.py", line 101, in run
    self._get_gen(us_instances, m, systemname, print_ont, log_time=self.time)
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\utils\utility.py", line 78, in timed
    result = method(*args, **kw)
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\vn.py", line 240, in _get_gen
    out = patterns.make(systemname, self.threshold, self.link)
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\pattern.py", line 26, in make
    self.onto = pf.make_patterns(self.user_stories, threshold)
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\pattern.py", line 229, in make_patterns
    pi.identify(story)
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\pattern.py", line 336, in identify
    self.identify_func_role(story)
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\pattern.py", line 377, in identify_func_role
    role.append(self.getwt(story.role.functional_role.main))
  File "C:\Code\Machine Learning\IIM\VN-2\VisualNarrator-master (1)\VisualNarrator-master\vn\pattern.py", line 477, in getwt
    if str.lower(token.text) == str.lower(wt.token.text):
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by MarcelRobeer** [comment]
Thanks for pointing this out. It should have resulted in an 'Could not find a functional role' error---which it will catch now.

The handling of the tree structure in spaCy has been updated, so the behavior of `token.head` changed, which caused this error. I have changed it now to handle the new version of spaCy.

**Comment by ashwarhussain** [comment]
Hello Marcel, 

could not find you email id so taking this route of communicating with you.

You have thought about getting more details from Acceptance Criteria in a user story and using this extra information so make it more comprehensive. Any views on this idea?
