### ISSUE TITLE
Data Indexing problem

### ISSUE THREAD

**Issue by bikashg** [MarcelRobeer/VisualNarrator#8]
I tried to run the software against this sentence : 

As a Researcher I want to be able to reference a remote controlled vocabulary for my dataset so that I can be sure that columns of my tabular dataset are valid against a single shared list of terms.

and I get the following error : 

Traceback (most recent call last):
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1434, in _has_valid_type
    error()
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [I] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bikashg/Desktop/remote/userstories/lib/VisualNarrator/run.py", line 323, in <module>
    program()
  File "/home/bikashg/Desktop/remote/userstories/lib/VisualNarrator/run.py", line 311, in program
    return main(args.filename, args.system_name, args.print_us, args.print_ont, args.statistics, args.link, args.prolog, args.json, args.per_role, args.threshold, args.base_weight, weights, spacy_nlp)
  File "/home/bikashg/Desktop/remote/userstories/lib/VisualNarrator/run.py", line 84, in main
    matrices = matrix.generate(us_instances, ' '.join(success_stories), nlp)
  File "/home/bikashg/Desktop/remote/userstories/lib/VisualNarrator/vn/matrix.py", line 41, in generate
    w_us = self.remove_indicators(w_us, stories, nlp)
  File "/home/bikashg/Desktop/remote/userstories/lib/VisualNarrator/vn/matrix.py", line 241, in remove_indicators
    if matrix.loc[indicator, 'sum'] > 0:
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 836, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1551, in _getitem_axis
    self._has_valid_type(key, axis)
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1442, in _has_valid_type
    error()
  File "/home/bikashg/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [I] is not in the [index]'

**Comment by gglucass** [comment]
How are you asking Visual Narrator to analyze this user story? Do you happen to be using some sort of text file that may be formatted in a non-supported manner?

**Comment by bikashg** [comment]
No, its a regular text file. When I put some other user stories in the same file, I receive the parse results but for the sentence above, I receive the key indexing error.

**Comment by MarcelRobeer** [comment]
The issue causing this problem is related to the _lemma_ of 'I' being converted to -PRON- in some rare cases (see the ongoing issue in [https://github.com/explosion/spaCy/issues/962](https://github.com/explosion/spaCy/issues/962)). causing "I" to turn up as "-PRON-" in the index of the matrix. In the latest commit I fixed the issue with a quickfix.
